### ISSUE TITLE
Pull Icons from website

### ISSUE THREAD

**Issue by jkernsjr** [raivo-otp/ios-application#231] opened 2023-02-28 03:41 UTC
Is there a way that the app can pull the icon automatically from the website that you are inputting like other OTP apps do? If not, is there an easier way to send one in as opposed to the one currently on Github?

**Comment by mzch** [comment] 2023-02-28 19:00
👍  + loading icons from iCloud Drive.

**Comment by tijme** [comment] 2023-03-15 18:47
Duplicate of #67

**Closed by tijme** 2023-03-15 18:47 UTC
