### ISSUE TITLE
Unencrypting exported ZIP not working with 7-Zip

### ISSUE THREAD

**Issue by makua-bernal** [raivo-otp/ios-application#160] opened 2022-08-20 16:03 UTC
**A quick summary and/or background**

I am not able to unencrypt the exported Raivo OTP backup on Windows 10 with 7-Zip

**Steps to reproduce**

1. Set up app
2. Export encrypted OTPs to iCloud
3. Extract successfully with password on iOS
4. Copy zip from iCloud to Windows
5. Extract with same (copied) password causes error on Windows

**What you expected would happen**

The .json and .html files are successfully extracted from the zip archive.

**What actually happens**

The .json and .html files are empty and an error is shown indicating a false password

**Notes**

Password is 32 characters and consists of ascii and special symbols \\:<‘,/;

App version 1.4.3

**Comment by tijme** [comment] 2022-08-20 20:03
Have you tried another ZIP client (e.g. the build in Windows ZIP client)?

**Comment by makua-bernal** [comment] 2022-08-20 20:10
I also tried the built in Windows tool and it unfortunately did not work.

**Comment by tijme** [comment] 2022-08-20 20:20
Hmm, that's weird. Are you a 100% certain that you've noted down the correct password?

**Comment by makua-bernal** [comment] 2022-08-20 20:21
Yeah I am copying it from a password manager on both sides.

**Comment by tijme** [comment] 2022-08-21 18:08
Are you able to replicate the issue? In that case I would love to get a ZIP file + password that you are not able to decrypt. It helps me debug the issue.

Currently I can't reproduce it unfortunately. I used the password `2Nt3Bt‘,/;<:\PCD4!xMlik&wmT@ZDO2` and tried to decrypt the archive itself on my iDevice, which worked.

**Comment by makua-bernal** [comment] 2022-08-21 18:14
Decrypting the ZIP file on iOS works for me too, it's on Windows that causes problems. Did you try it on Windows by chance?

**Comment by tijme** [comment] 2022-08-21 18:21
Alright, quite interesting. I'm able to reproduce it now. No idea what's happening here. Something with encoding maybe?

**Comment by makua-bernal** [comment] 2022-08-21 18:26
Yeah I thought that too, I checked the ‘ symbol and it was the same utf-8 character, but didn't check any others. Could be similar to the issue with the £ sign?

**Comment by tijme** [comment] 2022-08-21 18:33
Yeah, that's what I thought as well. I just checked this with the AES export and it's the same, can't decrypt it with this password on Windows. Extracting it on the iDevice device itself works. Really interesting use case. 

It seems that I cannot create a ZIP using 7-Zip with a `‘` in the password either.

**Comment by tijme** [comment] 2022-08-21 18:38
Alright, I found the issue. Apparently it lies in the ZIP utilities on Windows, which cannot handle certain UTF8 chars, while the Apple built-in utility can. I'm going to close this and track the issue further in #153.

Thanks for reporting and helping me debug @makua-bernal!

**Closed by tijme** 2022-08-21 18:38 UTC
Labels: Extra input required
