### ISSUE TITLE
Raivo OTP exporting 'empty' zip archive.

### ISSUE THREAD

**Issue by TechNerd-019** [raivo-otp/ios-application#146] opened 2022-07-15 08:05 UTC
**Describe the bug**
When exporting a .zip archive of my Raivo OTP database, the archive appears to be 'empty'. Extracted using 'The Unarchiver' on OS X as suggested by the app. Nothing was extracted. No password was prompted either.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'.
2. Click on 'Export OTPs to ZIP archive'.
3. Click on 'Export'.
4. Attempt extracting the archive after it has been exported.

**Expected behavior**
The unarchiver app should ask for my password, which is the password I used to set-up my Raivo OTP database when I first installed the app. Upon entering the password successfully, the archive contents are extracted.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 15.5
 - App Version: 1.4.0

**Additional context**
I do not use iCloud for syncing as I prefer manually backing up my data to external hard drives (I use offline account). This bug prevents me from seeing my exported TOTP QR codes from the .zip file. The only workaround I can think of is taking an individual picture of each QR code and saving them by title.

**Comment by helmarw** [comment] 2022-07-15 08:41
duplicate, see https://github.com/raivo-otp/ios-application/issues/134

**Comment by tijme** [comment] 2022-07-21 08:22
Duplicate of #134.

**Closed by tijme** 2022-07-21 08:22 UTC
Labels: Bug
