### ISSUE TITLE
iOS app not exporting backup ZIP properly 

### ISSUE THREAD

**Issue by TheCaptRay** [raivo-otp/ios-application#138] opened 2022-06-18 17:50 UTC
iOS app is not exporting backup OTPs ZIP properly. When I open the exported ZIP its empty. 

1. Go to Settings
2. Click on Export Encrypted ZIP
3. Open the encrypted file using 7zip or other software. 
4. It’s empty.

**Expected behavior**
The exported ZIP should be exporting backup of OTPs in an encrypted ZIP. It was previously working fine.

 - Device: iPhone 13
 - OS: 15.5
 - Version 1.4.0 build 60

**Comment by redac** [comment] 2022-07-03 09:50
Is there any other way to export OTPs at the moment? i've got 10+ and really want to avoid turning them off and on.

**Comment by Tomatillone** [comment] 2022-07-06 13:17
You could swipe left on an item and scan or screenshot the QR code for each token.

**Comment by tijme** [comment] 2022-07-21 08:22
Duplicate of #134.

**Closed by tijme** 2022-07-21 08:22 UTC
Labels: Bug
