### ISSUE TITLE
Tokens are not syncing between devices

### ISSUE THREAD

**Issue by tcapote** [raivo-otp/ios-application#245] opened 2023-04-09 04:06 UTC
I am using an iPhone 14 Pro Max (16.4) and an iPad M1 Pro (16.4). The apps sync to the same iCloud account. They are reading the data from iCloud, as I can log into both apps/devices and get the token data as expected.

What seems to be happening now is that I just added to more tokens (BeyondTrust) on my iPhone. I checked my iPad a few days later, and do not see these tokens sync'd on my iPad.

I deleted the iPad data and app, and reinstalled on my iPad. It sync'd the data from iCloud, but not the two BeyondTrust tokens, they are not there. I verified they are on my iPhone still. I deleted the data and app from both devices, just installed on my iPhone, the BeyondTrust tokens were not there. I recreated two tokens on the iPhone. after about 30 minutes, I re-installed the app on my iPad and sync'd with iCloud, and the Tokens are not there?

The status shows "Syncing up-to-date" on both devices. not sure where to go form here? Seems the syncing is no longer working for me?

Thanks in advance for your help!

**Comment by tijme** [comment] 2023-04-10 13:16
Can you edit the one on your iPhone and save it again? That should re-push it to your iPad.

**Comment by tcapote** [comment] 2023-04-10 18:24
Thanks for the quick response! I had removed the App and Data from the iPad. I added the two Tokens on to my iPhone. Waited a day, and then re-installed the app on my iPad. My data was sync'd with iCloud, but the two tokens I added the day before were not there.

I took your suggestions and edited them both, and they showed up on the iPad within 15 seconds. 

Could it be that they both had the same "Title" name? Is there a way to force a sync?

Thanks for all your help, great app and support!

**Comment by tijme** [comment] 2023-04-12 06:19
Seems like there is an issue with syncing sometimes. Did the tokens on your iPhone show a lightning strike icon (indicating that they weren't saved to iCloud)? Or not?

Anyhow, I've had 2 or 3 other users report this as well. Haven't been able to reproduce this myself yet. Are you able to reproduce it?

**Comment by tijme** [comment] 2023-04-14 06:41
Thank you for reporting and helping to debug. I'm closing this as a duplicate of #220 so it can be tracked in that issue.

**Closed by tijme** 2023-04-14 06:41 UTC
Labels: Bug
