### ISSUE TITLE
Unlock with touchID or FaceID by default when opening the APP

### ISSUE THREAD

**Issue by f2sky** [raivo-otp/ios-application#28] opened 2020-12-04 06:26 UTC
When I open the APP, the default unlock method is to enter the unlock passcode,please change to unlock with touchID or FaceID by default.

**Comment by tijme** [comment] 2021-01-20 11:21
I think this is a duplicate of #25, which has been fixed and released to the AppStore.

**Closed by tijme** 2021-01-20 11:21 UTC
Labels: Feature request
