### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by Peter9936** [raivo-otp/ios-application#32] opened 2020-12-11 09:01 UTC
Hi,

Thanks for this great app! Would it be possible for native iPad support? 

Kind regards

**Comment by tijme** [comment] 2020-12-11 10:58
Closing this as it's a duplicate of #18.

I would love to improve the user experience on iPad's when I have the time. Feel free to contribute if you want!

**Closed by tijme** 2020-12-11 10:58 UTC
