### ISSUE TITLE
Exporting a zip to file storage doesn't finish (visually)

### ISSUE THREAD

**Issue by valynor** [raivo-otp/ios-application#48] opened 2021-06-11 14:31 UTC
iPhone 8, iOS 14.6, Raivo 1.1.16

Exporting a zip to iCloud or local storage works but the process never finishes visually (the spinner on the "Export" button at the bottom of the screen never stops, which is quite confusing because you don't get feedback that the Export has, in fact, finished). 

The zip seems to be exported correctly nevertheless.

**Comment by tijme** [comment] 2021-06-13 09:16
Thanks for the bug report @valynor,

Would you mind taking a screencapture (video) of the bug? I'm not experiencing the bug myself, which makes it a little bit more difficult for me to debug.

Thanks in advance!

**Comment by valynor** [comment] 2021-06-13 12:00
@tijme 

Here you go:

https://user-images.githubusercontent.com/23384233/121806295-858c9e00-cc4f-11eb-8bab-e10358b0e72c.mp4

The zip (<200kb) appeared in my icloud after a few seconds but the spinner never stops.

**Comment by tijme** [comment] 2021-06-13 12:08
Greatly appreciated. Turns out it works with the export options I used during development, but it doesn't work when you save it to your files. Bug confirmed. I'll be trying to fix this soon 👍

**Comment by valynor** [comment] 2021-06-13 12:10
Sweet, thank you!

**Comment by tijme** [comment] 2021-06-13 12:33
Fixed in TestFlight version 1.1.18 (https://github.com/raivo-otp/ios-application/releases/tag/build-37). Will be released after a testing phase.

**Closed** 2021-06-13 12:37 UTC
Labels: Bug
