### ISSUE TITLE
Export function generates empty zip file

### ISSUE THREAD

**Issue by avayl** [raivo-otp/ios-application#139] opened 2022-06-20 18:58 UTC
**Describe the bug**
When exporting OTPs to Zip archive the generated file is always 22 bytes and empty. Tried opening with unarchiver on macos and tried sharing using different apps (telegram, airdrop, gmail)

**To Reproduce**
1. Try to export file

**Expected behavior**
Expect a file with my OTP backup

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 15.5

**Additional context**
Using the latest app from the app store.

**Comment by RivenNero** [comment] 2022-06-27 19:44
Same here.

**Comment by ewollesen** [comment] 2022-06-28 06:28
See also #138.

**Comment by Johan446** [comment] 2022-07-10 20:01
Same here. Always 22 bytes

**Comment by tijme** [comment] 2022-07-21 08:22
Duplicate of #134.

**Closed by tijme** 2022-07-21 08:22 UTC
Labels: Bug
