### ISSUE TITLE
Export is not working on iOS

### ISSUE THREAD

**Issue by Domessy** [raivo-otp/ios-application#134] opened 2022-06-13 08:38 UTC
**Describe the bug**
**Raivo OTP
Version 1.4.0 (build-60)**

The export functionality seems broken.
When you click to export, it is creating a 22 bytes .zip archive that is empty when opened with a computer using 7zip.
The archive doesn't require the password to be opened.
When using export, I tried "Save to files" and also "Send email", but it doesn't change the fact that archive seems corrupted.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Export OTPs to ZIP archive'
3. Click on 'Export'
4. See that the archive created is 22 bytes.
5. Save it or send it to a compteur.
6. Open it.

**Expected behavior**
The archive should be larger.
The archive should ask for a password.
The archive should not be empty.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS
 - Version: 15.5

**Additional context**
It used to work fine with my device.
It is the first time I try export since iOS 15.5 and since Raivo OTP update 1.4.0.

**Comment by scheralph** [comment] 2022-06-14 02:23
Just chiming in as I'm seeing _exactly_ the same issue and behaviour here, on a different device.
I tried
- saving to files (iCloud Drive)
- saving to files (Local directory)
- sharing via Email
The issue persists across all ways of sharing the exported file.

**Raivo OTP
Version 1.4.0 (build-60)**

**Smartphone (please complete the following information):**
    Device: iPhone SE (2020)
    OS: iOS
    Version: 15.5
    TouchID enabled for unlocking RaivoOTP

Let me know if I can help narrow down the cause any further :)

**Comment by ben-denzler** [comment] 2022-06-18 18:09
I'm having the same problem, 7zip doesn't ask for a password when opening it and the zip is empty. I tried saving the zip by sharing through Discord and OneDrive.

Device: iPhone X
OS: iOS
Version: 15.5

**Comment by tijme** [comment] 2022-06-19 08:03
Bug confirmed. Sorry for this issue, as it's one of the most important features. Will see if I can start working on a fix soon.

**Comment by ewollesen** [comment] 2022-06-28 06:29
#138 and #139 are likely duplicates.

**Comment by tympom** [comment] 2022-07-04 20:28
> Bug confirmed. Sorry for this issue, as it's one of the most important features. Will see if I can start working on a fix soon.

any progress on this?

**Comment by tympom** [comment] 2022-07-05 04:40
More than 3 weeks and nothing happens, "Copyright (c) 2021"... Is this projecect abandoned? 🤔

**Comment by tijme** [comment] 2022-07-05 04:45
Nope. I'm on holidays so I can't work on it at the moment. Feel free to contribute with a fix and I'm happy to merge.

**Comment by tympom** [comment] 2022-07-05 04:58
> Nope. I'm on holidays so I can't work on it at the moment. Feel free to contribute with a fix and I'm happy to merge.

Happy to hear as this is the best authenticator for iOS 😃 Specifically the encrypted export with QR codes etc is/was 👍🏻 
I am not an iOS programmer but cannot find a commit that could impact export in the last few months 🤔

**Comment by vbuser2004** [comment] 2022-07-07 23:55
> Nope. I'm on holidays so I can't work on it at the moment. Feel free to contribute with a fix and I'm happy to merge.

Thanks for all your work on this project @tijme! Enjoy your holiday & thanks again for taking the time to make & improve this useful app.

**Comment by helmarw** [comment] 2022-07-14 09:36
i just tried to Run Raivo Debug in the simulator (Target iPhone 12 Pro Max)
after solving a few problems also realizing that the reository-version is 1.3.0-53 and the release version is 1.4.0-60
i got it to work including zip-export within the Simulator but only version 1.3.0, somehow i cant get the 1.4..0 to compile
One thing i noticed but is that the Package Dependencies for ZipArchive was in both 1.3.0 and 1.4.0 version 2.4.2
the newest version but is 2.5.2, maybe thats a point that could be looked at ... 
but in version 1.3.0 it does not make a differecne zip-export works with 2.4.2 and 2.5.2

im still trying to compile the release version 1.4.0-60 to try both zipArchive dependencies but no luck for now
![image](https://user-images.githubusercontent.com/10408121/178948351-a52f5616-4a65-4529-a3d4-40915809df6b.png)

**Comment by tijme** [comment] 2022-07-21 09:03
Above commit fixes the issue. This will take a few weeks to get to release, as it has to go through (beta) testing and the Apple Review process.

**Comment by tijme** [comment] 2022-07-22 10:46
Closing this issue as it will be pushed to public soon (within a few weeks).

**Closed by tijme** 2022-07-22 10:46 UTC
Labels: Bug

**Comment by tijme** [comment] 2022-07-25 15:56
Fix is published to the App Store. If you update you should be good and you can export some ZIP archives again :)

**Comment by Johan446** [comment] 2022-07-25 16:15
Amazing! Thanks. Now it works again.
