### ISSUE TITLE
Not working with unsynched clock

### ISSUE THREAD

**Issue by AndresGlez** [raivo-otp/ios-application#102] opened 2022-01-26 21:34 UTC
**Describe the bug**
My phone is 11 minutes advanced in time. The application does not work.

**To Reproduce**
- Advance clock 11 minutes.
- Scan QR code to add password (I tried with Twitter).
- Write test code to finish password addition.
- Code does not work.

**Expected behavior**
Detect clock is out of synch and take it into account (Authy works like that).

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS15.2.1
 - Version: I don’t know 

**Additional context**

**Comment by tijme** [comment] 2022-01-27 19:01
Hi @AndresGlez,

This is correct and not a bug. TOTP's are generated based on the current time. If the time on your iPhone is incorrect the TOTP time will be incorrect. Currently, the only way that I know of to resolve this is to ping an NTP server, which I do not want to communicate with due to privacy reasons.

**Closed by tijme** 2022-01-27 19:01 UTC
Labels: Bug

**Comment by AndresGlez** [comment] 2022-01-27 19:19
Hi @tijme,

Thanks for your reply. I completely understand your point.

Could it be possible to add a configuration to manually advance or delay the number of seconds the user wants? It may sound strange, but I need to have my clock set 11 minutes in the future :)

Cheers!
